version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: UrlShortener.API/Dockerfile
    container_name: urlshortener_api
    ports:
      - "5005:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=url_shortener;Username=postgres;Password=postgres
      
  db:
    image: postgres:15
    container_name: urlshortener_db
    restart: always
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: